# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
    build:
        docker:
            - image: circleci/python:3.7.3
        steps:
            - run:
                name: Install Pipenv
                comand: |
                    pip install pipenv
                    pipenv install
            - run:
                name: Test
                command: test/test.sh

